spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd

application:
  sites:
    -
      url: https://lenta.ru
      name: Lenta.ru
    -
      url: https://skillbox.ru
      name: Skillbox

#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: TRACE

#debug: true
logging.level.ru.javanatnat.sitesearchengine.service.*: DEBUG
